import type {Campaign, CollectionDefinition, Product} from './types';

/**
 * MOCK CATALOGUE — development only.
 *
 * Titles, prices and copy are drafts to exercise the Golden Path. Replace with
 * Shopify products + metafields before launch. Worked examples use fictional
 * figures and say so on the page.
 */

const EXAMPLE_NOTE = 'Illustrative example with fictional figures.';

export const MOCK_PRODUCTS: Product[] = [
  {
    universe: 'pro',
    handle: 'job-margin-calculator',
    factoryId: 'A02',
    title: 'Job Margin Calculator',
    tagline: 'See your real margin on every job before you send the quote.',
    priceCents: 1200,
    format: 'Spreadsheet calculator',
    formats: ['xlsx', 'sheets', 'pdf'],
    timeToValue: '15 min to your first checked quote',
    publishedAt: '2026-06-02',
    problem: {
      headline:
        'You price jobs on gut feeling and discover the margin after the invoice.',
      points: [
        'Materials, travel and extra hours eat the profit you thought you had.',
        'Two similar jobs can differ by 20 margin points without you noticing.',
        'You can’t tell which type of job is actually worth taking.',
      ],
    },
    outcome: {
      headline: 'A margin figure on every job, before you commit to a price.',
      points: [
        'Materials, labour, travel and subcontracting in one line per job.',
        'Margin in € and %, with a warning under your minimum threshold.',
        'Compare up to 30 jobs side by side to see what really pays.',
      ],
    },
    included: [
      {name: 'Job Margin Calculator', format: 'xlsx', detail: 'Calculator + 30-job comparison tab'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Copy-to-Drive link, same formulas'},
      {name: 'Quick-start guide', format: 'pdf', detail: '4 pages, setup + worked example'},
    ],
    howItWorks: [
      'Enter your hourly cost and minimum target margin once.',
      'Fill one line per job: materials, hours, trips, subcontracting.',
      'Read the margin and adjust the price before the quote goes out.',
    ],
    example: {
      title: 'Bathroom refit quoted at €4,800',
      setup: 'Materials €1,950 · 38 h at €34/h cost · 6 trips at €25 · €400 tiling subcontractor',
      result: 'Real margin: €1,008 (21%), not the 35% assumed when quoting',
      note: EXAMPLE_NOTE,
    },
    faq: [
      {
        q: 'Do I need Excel?',
        a: 'No. It works in Excel 2016 or later, Google Sheets and LibreOffice Calc.',
      },
    ],
    preview: {kind: 'sheet'},
    offer: {
      tier: 'impulse',
      problemTags: ['profit'],
      businessTags: ['artisans'],
      crossSells: [
        {handle: 'intervention-rate-calculator', priority: 100, reason: 'Sets the hourly cost this calculator uses for labour.'},
        {handle: 'quote-invoice-kit', priority: 80, reason: 'Turns the margin-checked price into a clean quote.'},
        {handle: 'cash-flow-dashboard', priority: 60, reason: 'Shows when that margin actually lands in your account.'},
      ],
      bundleUpgrade: {handle: 'artisan-business-toolkit', headline: 'Get the full Artisan Business Toolkit'},
      progressOffer: {campaignId: '3-tools-20'},
      badges: ['featured'],
    },
  },
  {
    universe: 'pro',
    handle: 'intervention-rate-calculator',
    factoryId: 'A03',
    title: 'Hourly Rate Calculator',
    tagline: 'Find the minimum hourly rate that covers your costs, charges and unpaid hours.',
    priceCents: 900,
    format: 'Spreadsheet calculator',
    formats: ['xlsx', 'sheets', 'pdf'],
    timeToValue: '10 min',
    publishedAt: '2026-05-20',
    problem: {
      headline: 'Your hourly rate was copied from a competitor, not calculated.',
      points: [
        'Admin, travel and quoting time are unpaid but still cost you.',
        'Social charges and insurance are missing from the rate.',
        'Raising prices feels risky because you don’t know your floor.',
      ],
    },
    outcome: {
      headline: 'A rate floor you can defend, and a target rate above it.',
      points: [
        'Break-even hourly rate from your real yearly costs.',
        'Target rate for the income you want, based on billable hours.',
        'Scenario table: what changes if you bill 5 more hours a week.',
      ],
    },
    included: [
      {name: 'Hourly Rate Calculator', format: 'xlsx', detail: 'Calculator + 3 scenarios'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Copy-to-Drive link'},
      {name: 'Quick-start guide', format: 'pdf', detail: '3 pages'},
    ],
    howItWorks: [
      'List your yearly fixed costs, charges and insurance.',
      'Estimate your truly billable hours per week.',
      'Read your break-even rate and your target rate.',
    ],
    example: {
      title: 'Solo electrician, 4 days on site per week',
      setup: '€21,000 yearly costs · €38,000 target income · 26 billable h/week, 46 weeks',
      result: 'Break-even €17.56/h · Target €49.33/h',
      note: EXAMPLE_NOTE,
    },
    faq: [
      {
        q: 'Does it handle my country’s social charges?',
        a: 'You enter your own charge rate, so it works for any country and status. The guide shows where to find the figure.',
      },
    ],
    preview: {kind: 'sheet'},
    offer: {
      tier: 'impulse',
      problemTags: ['profit'],
      businessTags: ['artisans', 'freelancers'],
      crossSells: [
        {handle: 'job-margin-calculator', priority: 100, reason: 'Applies your new rate to each job and checks the margin.'},
        {handle: 'freelance-pricing-workbook', priority: 70, reason: 'Moves you from hourly rates to priced packages.'},
        {handle: 'quote-invoice-kit', priority: 60, reason: 'Puts the new rate on a professional quote.'},
      ],
      bundleUpgrade: {handle: 'artisan-business-toolkit', headline: 'Get the full Artisan Business Toolkit'},
      progressOffer: {campaignId: '3-tools-20'},
      badges: ['featured'],
    },
  },
  {
    universe: 'pro',
    handle: 'quote-invoice-kit',
    factoryId: 'A04',
    title: 'Quote & Invoice Template Kit',
    tagline: 'Professional quotes and invoices with the terms that get you paid on time.',
    priceCents: 1900,
    format: 'Document templates',
    formats: ['docx', 'xlsx', 'sheets', 'pdf'],
    timeToValue: '30 min',
    publishedAt: '2026-04-11',
    problem: {
      headline: 'Your quotes look improvised, so clients take longer to say yes.',
      points: [
        'Quotes written in an email body or a blank Word file.',
        'No payment terms, so late payment becomes normal.',
        'No deposit clause, so you finance the materials yourself.',
      ],
    },
    outcome: {
      headline: 'Quotes and invoices that look established and set clear terms.',
      points: [
        'Quote template with good / better / best options.',
        'Invoice template with automatic totals, VAT and deposit lines.',
        '12 payment and deposit clauses ready to adapt.',
      ],
    },
    included: [
      {name: 'Quote templates', format: 'docx', detail: '3 layouts including options pricing'},
      {name: 'Invoice template', format: 'xlsx', detail: 'Auto totals, VAT, deposit deduction'},
      {name: 'Google Sheets invoice', format: 'sheets', detail: 'Same formulas'},
      {name: 'Clause library', format: 'pdf', detail: '12 payment and deposit clauses'},
    ],
    howItWorks: [
      'Add your logo, details and payment terms once.',
      'Duplicate the quote template for each job, pick a layout.',
      'Convert an accepted quote into an invoice in a few minutes.',
    ],
    faq: [
      {
        q: 'Are the invoices legally compliant in my country?',
        a: 'They include the fields most EU countries require (numbering, dates, parties, VAT). Mandatory mentions vary by country and legal status, so check them once with your accountant.',
      },
    ],
    preview: {kind: 'doc'},
    offer: {
      tier: 'core',
      problemTags: ['profit', 'organize'],
      businessTags: ['artisans', 'freelancers', 'agencies'],
      crossSells: [
        {handle: 'follow-up-script-pack', priority: 100, reason: 'Follow up the quotes you send instead of waiting.'},
        {handle: 'job-margin-calculator', priority: 80, reason: 'Check the margin before the price goes on the quote.'},
        {handle: 'client-onboarding-workbook', priority: 50, reason: 'Start accepted jobs with scope and payment agreed.'},
      ],
      bundleUpgrade: {handle: 'artisan-business-toolkit', headline: 'Get the full Artisan Business Toolkit'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'follow-up-script-pack',
    factoryId: 'A06',
    title: 'Quote Follow-Up Script Pack',
    tagline: 'Follow up every quote without sounding pushy — email, SMS and phone.',
    priceCents: 900,
    format: 'Script pack',
    formats: ['pdf', 'docx'],
    timeToValue: '5 min',
    publishedAt: '2026-09-08',
    problem: {
      headline: 'Quotes go out and you never hear back.',
      points: [
        'You don’t follow up because it feels pushy.',
        'No clear moment to call, text or email.',
        'Many lost quotes aren’t lost on price — they’re simply forgotten.',
      ],
    },
    outcome: {
      headline: 'A follow-up sequence you can send on autopilot, in your own tone.',
      points: [
        'Day 2, day 7 and day 14 messages for email, SMS and phone.',
        'Replies to “too expensive”, “not now” and “we’ll think about it”.',
        'A closing message that keeps the door open.',
      ],
    },
    included: [
      {name: '24 follow-up scripts', format: 'pdf', detail: 'Email, SMS and phone versions'},
      {name: 'Editable scripts', format: 'docx', detail: 'Adapt tone and details'},
      {name: 'Timing card', format: 'pdf', detail: '1 page: when to send what'},
    ],
    howItWorks: [
      'Pick the tone that fits you: formal or friendly.',
      'Copy the day-2 message into your phone or email templates.',
      'Send the next step on day 7 and day 14 if there’s no reply.',
    ],
    example: {
      title: 'Kitchen fitter sending 12 quotes a month',
      setup: 'Before: no follow-up. After: day-2 SMS and day-7 email on every open quote.',
      result: 'Every open quote gets 2 follow-ups instead of 0, in about 3 minutes each',
      note: 'We don’t promise a win rate — that depends on your market and prices.',
    },
    faq: [],
    preview: {kind: 'scripts'},
    offer: {
      tier: 'impulse',
      problemTags: ['find-clients'],
      businessTags: ['artisans', 'freelancers', 'agencies'],
      crossSells: [
        {handle: 'prospecting-tracker', priority: 90, reason: 'Schedules each follow-up so none slips.'},
        {handle: 'quote-invoice-kit', priority: 80, reason: 'Sends quotes worth following up on.'},
        {handle: 'review-request-kit', priority: 50, reason: 'Once the job is done, asks for the review.'},
      ],
      bundleUpgrade: {handle: 'artisan-business-toolkit', headline: 'Get the full Artisan Business Toolkit'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'google-business-profile-checklist',
    factoryId: 'A07',
    title: 'Google Business Profile Checklist',
    tagline: 'Complete and activate your Google profile so nearby clients find you first.',
    priceCents: 700,
    format: 'Checklist',
    formats: ['pdf', 'sheets'],
    timeToValue: '45 min to complete',
    publishedAt: '2026-03-15',
    problem: {
      headline: 'Your Google profile is half filled, so nearby clients pick a competitor.',
      points: [
        'Categories, services and hours left on default.',
        'No photos, no posts, unanswered questions.',
        'No idea what Google uses to rank local results.',
      ],
    },
    outcome: {
      headline: 'A complete, active profile in one sitting.',
      points: [
        '42-point checklist, ordered by impact.',
        'Category and service wording examples by trade.',
        'A 15-minute monthly maintenance routine.',
      ],
    },
    included: [
      {name: 'Profile checklist', format: 'pdf', detail: '42 points, printable'},
      {name: 'Progress tracker', format: 'sheets', detail: 'Tick off and date each point'},
    ],
    howItWorks: [
      'Open your profile and the checklist side by side.',
      'Work through the points top to bottom — highest impact first.',
      'Set the monthly routine as a recurring reminder.',
    ],
    faq: [],
    preview: {kind: 'checklist'},
    offer: {
      tier: 'impulse',
      problemTags: ['local', 'marketing'],
      businessTags: ['artisans', 'local-shops'],
      crossSells: [
        {handle: 'review-request-kit', priority: 100, reason: 'Reviews are the next lever once the profile is complete.'},
        {handle: 'local-seo-action-kit', priority: 80, reason: 'Goes past the profile: local pages, citations, links.'},
      ],
      bundleUpgrade: {handle: 'local-visibility-bundle', headline: 'Get the complete Local Visibility Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'review-request-kit',
    factoryId: 'A08',
    title: 'Review Request Kit',
    tagline: 'Ask every happy client for a Google review, at the right moment.',
    priceCents: 900,
    format: 'Templates + print files',
    formats: ['docx', 'pdf', 'canva'],
    timeToValue: '20 min',
    publishedAt: '2026-05-05',
    problem: {
      headline: 'Satisfied clients rarely leave reviews unless you ask — and asking feels awkward.',
      points: [
        'Your best work leaves no trace online.',
        'A competitor with 80 reviews wins the click over your 6.',
        'One negative review sits unanswered at the top.',
      ],
    },
    outcome: {
      headline: 'A simple routine that asks every satisfied client.',
      points: [
        'SMS, email and WhatsApp request templates.',
        'Printable QR card and invoice insert.',
        'Reply templates for positive and negative reviews.',
      ],
    },
    included: [
      {name: 'Request templates', format: 'docx', detail: '12 messages'},
      {name: 'QR review card', format: 'canva', detail: 'Business-card and A6 formats'},
      {name: 'Print-ready card', format: 'pdf', detail: 'Same designs, ready to print'},
      {name: 'Reply templates', format: 'pdf', detail: '10 replies, including negative reviews'},
    ],
    howItWorks: [
      'Add your review link to the QR card and templates.',
      'Send the request the day the job is finished.',
      'Reply to every review within a week using the templates.',
    ],
    faq: [
      {
        q: 'Does this involve buying or rewarding reviews?',
        a: 'No. The kit only covers asking real clients. Offering rewards for reviews breaks Google’s policies and consumer law in many countries.',
      },
    ],
    preview: {kind: 'scripts'},
    offer: {
      tier: 'impulse',
      problemTags: ['local', 'marketing'],
      businessTags: ['artisans', 'local-shops'],
      crossSells: [
        {handle: 'google-business-profile-checklist', priority: 100, reason: 'Makes sure the profile clients land on is complete.'},
        {handle: 'local-seo-action-kit', priority: 70, reason: 'Turns reviews into local search rankings.'},
      ],
      bundleUpgrade: {handle: 'local-visibility-bundle', headline: 'Get the complete Local Visibility Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'cash-flow-dashboard',
    factoryId: 'A09',
    title: '13-Week Cash Flow Dashboard',
    tagline: 'Know your cash position 13 weeks ahead, in 10 minutes a week.',
    priceCents: 2900,
    format: 'Spreadsheet dashboard',
    formats: ['xlsx', 'sheets', 'pdf'],
    timeToValue: '1 hour setup, then 10 min a week',
    publishedAt: '2026-02-10',
    problem: {
      headline: 'You’re profitable on paper but tense every time a big bill is due.',
      points: [
        'Client payments and supplier bills don’t line up.',
        'VAT and tax payments arrive as surprises.',
        'You can’t tell if you can afford a hire or a new van.',
      ],
    },
    outcome: {
      headline: 'A 13-week view of cash in and out, with warnings before it’s tight.',
      points: [
        'Weekly in/out forecast with low-cash warnings.',
        'Scenario toggles: late client payment, new expense.',
        'A one-page chart to share with your accountant or bank.',
      ],
    },
    included: [
      {name: 'Cash flow dashboard', format: 'xlsx', detail: 'Forecast, actuals and chart tabs'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Copy-to-Drive link'},
      {name: 'Setup guide', format: 'pdf', detail: '8 pages'},
    ],
    howItWorks: [
      'Enter your opening balance and recurring costs.',
      'Add expected client payments and known bills by week.',
      'Update actuals weekly; the forecast and warnings follow.',
    ],
    example: {
      title: 'Small agency with 3 retainer clients',
      setup: '€18,400 expected in and €15,900 out over 13 weeks · one client pays 30 days late',
      result: 'Week 7 drops to −€2,300 — visible 6 weeks in advance',
      note: EXAMPLE_NOTE,
    },
    faq: [],
    preview: {kind: 'dashboard'},
    offer: {
      tier: 'core',
      problemTags: ['profit', 'organize'],
      businessTags: ['artisans', 'freelancers', 'agencies', 'ecommerce', 'local-shops'],
      crossSells: [
        {handle: 'job-margin-calculator', priority: 70, reason: 'Makes sure each job adds to the cash, not just the revenue.'},
        {handle: 'quote-invoice-kit', priority: 60, reason: 'Deposit clauses bring cash in earlier.'},
        {handle: 'ecommerce-profit-calculator', priority: 50, reason: 'Profit per product, for shops planning stock.'},
      ],
      bundleUpgrade: {handle: 'profit-control-bundle', headline: 'Get the complete Profit Control Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
      badges: ['featured'],
    },
  },
  {
    universe: 'pro',
    handle: 'job-crew-planner',
    factoryId: 'A10',
    title: 'Job & Crew Planner',
    tagline: 'One weekly board for jobs, crew and material orders.',
    priceCents: 1900,
    format: 'Spreadsheet planner',
    formats: ['xlsx', 'sheets', 'pdf'],
    timeToValue: '30 min',
    publishedAt: '2026-07-01',
    problem: {
      headline: 'Your schedule lives in your head, your phone and three WhatsApp groups.',
      points: [
        'Double bookings and forgotten site visits.',
        'No view of who is where next week.',
        'Materials arrive late because the start date wasn’t clear.',
      ],
    },
    outcome: {
      headline: 'Everyone knows where to be, and materials are ordered on time.',
      points: [
        'Weekly and monthly views that fill from one job list.',
        'Crew availability and holidays.',
        'Material order dates calculated from job start dates.',
      ],
    },
    included: [
      {name: 'Job & crew planner', format: 'xlsx', detail: 'Job list, weekly and monthly boards'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Shareable with your crew'},
      {name: 'Printable weekly board', format: 'pdf', detail: 'A3 and A4'},
    ],
    howItWorks: [
      'Add your crew and their days off.',
      'Enter each job with a start date, duration and materials lead time.',
      'Share the weekly board every Friday.',
    ],
    faq: [],
    preview: {kind: 'planner'},
    offer: {
      tier: 'core',
      problemTags: ['organize'],
      businessTags: ['artisans'],
      crossSells: [
        {handle: 'job-margin-calculator', priority: 70, reason: 'Checks the margin of each job you schedule.'},
        {handle: 'cash-flow-dashboard', priority: 60, reason: 'Lines up material spend with incoming payments.'},
      ],
      bundleUpgrade: {handle: 'artisan-business-toolkit', headline: 'Get the full Artisan Business Toolkit'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'client-onboarding-workbook',
    factoryId: 'A11',
    title: 'Client Onboarding Workbook',
    tagline: 'Start every project with scope, timing and payment agreed.',
    priceCents: 2400,
    format: 'Workbook + templates',
    formats: ['pdf', 'docx', 'notion'],
    timeToValue: '1 hour',
    publishedAt: '2026-08-28',
    problem: {
      headline: 'Every new client starts with scattered emails, missing files and fuzzy scope.',
      points: [
        'You chase logins and assets for two weeks.',
        'Scope creep starts on day one because nothing was written down.',
        'The first invoice surprises the client.',
      ],
    },
    outcome: {
      headline: 'A repeatable onboarding that makes you look organised from day one.',
      points: [
        'Welcome pack template and kickoff agenda.',
        'Intake questionnaire and asset checklist.',
        'Scope confirmation email and change-request form.',
      ],
    },
    included: [
      {name: 'Onboarding workbook', format: 'pdf', detail: '22 pages'},
      {name: 'Templates', format: 'docx', detail: '7 editable templates'},
      {name: 'Notion version', format: 'notion', detail: 'Duplicate into your workspace'},
    ],
    howItWorks: [
      'Work through the workbook once to define your process.',
      'Adapt the 7 templates to your service.',
      'Send the welcome pack within 24 h of every signed deal.',
    ],
    faq: [],
    preview: {kind: 'doc'},
    offer: {
      tier: 'core',
      problemTags: ['organize'],
      businessTags: ['freelancers', 'agencies'],
      crossSells: [
        {handle: 'quote-invoice-kit', priority: 90, reason: 'Aligns the quote and the scope confirmation.'},
        {handle: 'freelance-pricing-workbook', priority: 70, reason: 'Defines the packages you onboard clients into.'},
      ],
      bundleUpgrade: {handle: 'freelance-operating-system', headline: 'Get the full Freelance Operating System'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'freelance-pricing-workbook',
    factoryId: 'A12',
    title: 'Freelance Pricing & Packages Workbook',
    tagline: 'Turn hourly work into three packaged offers with prices you can explain.',
    priceCents: 2400,
    format: 'Workbook + calculator',
    formats: ['pdf', 'xlsx'],
    timeToValue: '2 hours',
    publishedAt: '2026-01-20',
    problem: {
      headline: 'You sell hours, so earning more means working more.',
      points: [
        'Clients compare your hourly rate with cheaper freelancers.',
        'Getting faster at your job lowers your income.',
        'You haven’t raised prices in two years.',
      ],
    },
    outcome: {
      headline: 'Three clear packages, priced on scope and value.',
      points: [
        'Package builder: scope, deliverables, price.',
        'Value-based pricing worksheet.',
        'Price increase announcement templates.',
      ],
    },
    included: [
      {name: 'Pricing workbook', format: 'pdf', detail: '28 pages with exercises'},
      {name: 'Package calculator', format: 'xlsx', detail: 'Cost, time and price per package'},
    ],
    howItWorks: [
      'List what you deliver today and how long it takes.',
      'Group it into three packages with the builder.',
      'Price each package with the calculator and announce it.',
    ],
    faq: [],
    preview: {kind: 'doc'},
    offer: {
      tier: 'core',
      problemTags: ['profit'],
      businessTags: ['freelancers', 'agencies'],
      crossSells: [
        {handle: 'intervention-rate-calculator', priority: 90, reason: 'Gives you the cost floor under every package.'},
        {handle: 'client-onboarding-workbook', priority: 70, reason: 'Onboards clients into the new packages.'},
      ],
      bundleUpgrade: {handle: 'freelance-operating-system', headline: 'Get the full Freelance Operating System'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'local-seo-action-kit',
    factoryId: 'A13',
    title: 'Local SEO Action Kit',
    tagline: 'A 30-day plan to show up when people search for your trade in your town.',
    priceCents: 2900,
    format: 'Action kit',
    formats: ['pdf', 'sheets'],
    timeToValue: '30-day plan, 20–40 min a day',
    publishedAt: '2026-04-02',
    problem: {
      headline: 'You’re on page 3 for “[your trade] + your town”.',
      points: [
        'Your website has no page per service or area.',
        'Directory listings show old phone numbers and addresses.',
        'You don’t know what to do first, so nothing gets done.',
      ],
    },
    outcome: {
      headline: 'A daily task list that gets your local presence fixed in 30 days.',
      points: [
        '30-day task plan, 20–40 minutes a day.',
        'Local service page template.',
        'Citation list and tracker for EU directories.',
      ],
    },
    included: [
      {name: '30-day plan', format: 'pdf', detail: 'One task per day, with instructions'},
      {name: 'Service page template', format: 'pdf', detail: 'Structure + example copy'},
      {name: 'Citation tracker', format: 'sheets', detail: '60 EU directories'},
    ],
    howItWorks: [
      'Run the day-1 audit to get your starting point.',
      'Do one task a day; each takes 20–40 minutes.',
      'Re-run the audit on day 30 and compare.',
    ],
    faq: [
      {
        q: 'Do you guarantee a ranking?',
        a: 'No one can honestly guarantee a Google position. The kit gives you the tasks that matter for local results; how fast you move depends on your area and competitors.',
      },
    ],
    preview: {kind: 'checklist'},
    offer: {
      tier: 'core',
      problemTags: ['local', 'marketing'],
      businessTags: ['local-shops', 'artisans'],
      crossSells: [
        {handle: 'google-business-profile-checklist', priority: 100, reason: 'Starts with the profile, the fastest local win.'},
        {handle: 'review-request-kit', priority: 80, reason: 'Adds the reviews that local rankings rely on.'},
        {handle: 'content-calendar-90-days', priority: 50, reason: 'Keeps the profile and pages active after day 30.'},
      ],
      bundleUpgrade: {handle: 'local-visibility-bundle', headline: 'Get the complete Local Visibility Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'prospecting-tracker',
    factoryId: 'A14',
    title: 'Prospecting & Follow-Up Tracker',
    tagline: 'A simple pipeline that tells you who to contact today.',
    priceCents: 1900,
    format: 'Spreadsheet CRM',
    formats: ['xlsx', 'sheets'],
    timeToValue: '20 min',
    publishedAt: '2026-06-18',
    problem: {
      headline: 'Leads live in your inbox and you forget who to call back.',
      points: [
        'A warm lead goes cold because you followed up three weeks late.',
        'You don’t know how many deals are in progress.',
        'CRM software feels like overkill for your size.',
      ],
    },
    outcome: {
      headline: 'One sheet, one “due today” list, no subscription.',
      points: [
        'Pipeline stages from first contact to signed.',
        '“Due today” view based on next-action dates.',
        'Monthly conversion and pipeline value summary.',
      ],
    },
    included: [
      {name: 'Prospecting tracker', format: 'xlsx', detail: 'Pipeline, due-today and summary tabs'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Works on your phone'},
    ],
    howItWorks: [
      'Import or type in your current leads.',
      'Set a next-action date for each one.',
      'Open the “due today” tab every morning.',
    ],
    faq: [],
    preview: {kind: 'sheet'},
    offer: {
      tier: 'core',
      problemTags: ['find-clients', 'organize'],
      businessTags: ['freelancers', 'agencies'],
      crossSells: [
        {handle: 'follow-up-script-pack', priority: 100, reason: 'Tells you what to say when the tracker says call.'},
        {handle: 'client-onboarding-workbook', priority: 60, reason: 'Takes over once the deal is signed.'},
      ],
      bundleUpgrade: {handle: 'freelance-operating-system', headline: 'Get the full Freelance Operating System'},
      progressOffer: {campaignId: '3-tools-20'},
      badges: ['featured'],
    },
  },
  {
    universe: 'pro',
    handle: 'content-calendar-90-days',
    factoryId: 'A15',
    title: '90-Day Social Content Calendar',
    tagline: 'Three months of posts planned in one afternoon.',
    priceCents: 1900,
    format: 'Planner + templates',
    formats: ['sheets', 'pdf', 'canva'],
    timeToValue: '1 hour to plan a month',
    publishedAt: '2026-03-01',
    problem: {
      headline: 'You post when you remember, then go silent for weeks.',
      points: [
        'Every post starts from a blank page.',
        'Your feed shows no recent work, so it looks inactive.',
        'Designing each visual takes longer than writing it.',
      ],
    },
    outcome: {
      headline: 'A steady posting rhythm without daily effort.',
      points: [
        '90 post ideas for local and service businesses.',
        'Planning sheet with a weekly rhythm.',
        '12 editable Canva templates.',
      ],
    },
    included: [
      {name: 'Content calendar', format: 'sheets', detail: '90 days, pre-filled ideas'},
      {name: 'Post idea bank', format: 'pdf', detail: '90 ideas by category'},
      {name: 'Visual templates', format: 'canva', detail: '12 editable designs'},
    ],
    howItWorks: [
      'Pick 2–3 posting days that you can keep.',
      'Fill a month from the idea bank in one sitting.',
      'Batch the visuals with the Canva templates.',
    ],
    faq: [],
    preview: {kind: 'planner'},
    offer: {
      tier: 'core',
      problemTags: ['marketing'],
      businessTags: ['local-shops', 'ecommerce', 'freelancers'],
      crossSells: [
        {handle: 'review-request-kit', priority: 70, reason: 'Turns new reviews into ready-made posts.'},
        {handle: 'google-business-profile-checklist', priority: 60, reason: 'Reuses your posts on your Google profile.'},
      ],
      bundleUpgrade: {handle: 'local-visibility-bundle', headline: 'Get the complete Local Visibility Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'ecommerce-profit-calculator',
    factoryId: 'A16',
    title: 'E-commerce Profit Calculator',
    tagline: 'Profit per product after ads, fees, shipping and returns.',
    priceCents: 1200,
    format: 'Spreadsheet calculator',
    formats: ['xlsx', 'sheets'],
    timeToValue: '15 min',
    publishedAt: '2026-09-01',
    problem: {
      headline: 'Revenue grows but the bank account doesn’t.',
      points: [
        'Ads, payment fees, shipping and returns aren’t in your product margin.',
        'You scale products that lose money after ads.',
        'You have no maximum cost per acquisition per product.',
      ],
    },
    outcome: {
      headline: 'A clear profit figure per product, and the ad spend it can afford.',
      points: [
        'Profit per order after cost of goods, fees, shipping, returns and ads.',
        'Break-even ROAS and max cost per acquisition per product.',
        'Ranking of products to push, fix or drop.',
      ],
    },
    included: [
      {name: 'Profit calculator', format: 'xlsx', detail: 'Up to 100 products'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Copy-to-Drive link'},
    ],
    howItWorks: [
      'Enter your fee, shipping and return settings once.',
      'Add cost of goods and ad cost per order for each product.',
      'Sort by profit per order and decide what to scale.',
    ],
    example: {
      title: 'Shop selling a €39 product',
      setup: 'Cost of goods €11 · shipping €5.20 · fees 3% · 6% returns · €9.50 ad cost per order',
      result: '€9.79 profit per order (25%) · break-even ROAS 2.02',
      note: EXAMPLE_NOTE,
    },
    faq: [],
    preview: {kind: 'sheet'},
    offer: {
      tier: 'impulse',
      problemTags: ['profit'],
      businessTags: ['ecommerce'],
      crossSells: [
        {handle: 'product-page-checklist', priority: 90, reason: 'Raises conversion on the products worth scaling.'},
        {handle: 'cash-flow-dashboard', priority: 70, reason: 'Plans stock purchases against cash.'},
      ],
      bundleUpgrade: {handle: 'profit-control-bundle', headline: 'Get the complete Profit Control Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'pro',
    handle: 'product-page-checklist',
    factoryId: 'A17',
    title: 'Product Page Conversion Checklist',
    tagline: 'Audit each product page and fix what stops visitors from buying.',
    priceCents: 900,
    format: 'Checklist + scoring sheet',
    formats: ['pdf', 'sheets'],
    timeToValue: '30 min per page',
    publishedAt: '2026-07-22',
    problem: {
      headline: 'Visitors land on your product pages and leave.',
      points: [
        'Shipping costs and delivery times are hidden until checkout.',
        'Photos don’t answer the questions buyers email you about.',
        'On mobile, the add-to-cart button is below three screens of text.',
      ],
    },
    outcome: {
      headline: 'A ranked list of fixes for every product page.',
      points: [
        '38 checks: photos, price, shipping, reviews, mobile.',
        'Scoring sheet to compare pages.',
        'Fix list ranked by effort and impact.',
      ],
    },
    included: [
      {name: 'Conversion checklist', format: 'pdf', detail: '38 checks with examples'},
      {name: 'Scoring sheet', format: 'sheets', detail: 'Score and compare pages'},
    ],
    howItWorks: [
      'Start with your 5 highest-traffic product pages.',
      'Score each page against the 38 checks.',
      'Fix the “low effort, high impact” items first.',
    ],
    faq: [],
    preview: {kind: 'checklist'},
    offer: {
      tier: 'impulse',
      problemTags: ['marketing', 'profit'],
      businessTags: ['ecommerce'],
      crossSells: [
        {handle: 'ecommerce-profit-calculator', priority: 90, reason: 'Shows which products are worth optimising first.'},
        {handle: 'content-calendar-90-days', priority: 50, reason: 'Drives steady traffic to the improved pages.'},
      ],
      progressOffer: {campaignId: '3-tools-20'},
    },
  },

  // ---------------------------------------------------------------- Bundles
  {
    universe: 'pro',
    handle: 'artisan-business-toolkit',
    factoryId: 'B01',
    title: 'Artisan Business Toolkit',
    tagline: 'Price, quote, follow up, plan and collect reviews — six tools for trade businesses.',
    priceCents: 5900,
    format: 'Bundle · 6 tools',
    formats: ['xlsx', 'sheets', 'docx', 'pdf', 'canva'],
    timeToValue: 'Start with any tool today',
    publishedAt: '2026-06-10',
    bundleItems: [
      'intervention-rate-calculator',
      'job-margin-calculator',
      'quote-invoice-kit',
      'follow-up-script-pack',
      'job-crew-planner',
      'review-request-kit',
    ],
    problem: {
      headline: 'Running a trade business means quoting, chasing, planning and invoicing — mostly in the evening.',
      points: [
        'Prices that don’t cover the real hours.',
        'Quotes that go unanswered.',
        'A schedule that only exists in your head.',
      ],
    },
    outcome: {
      headline: 'One set of tools that covers a job from quote to review.',
      points: [
        'Know your rate and your margin before you quote.',
        'Send professional quotes and follow them up.',
        'Plan the crew, then collect the review.',
      ],
    },
    included: [],
    howItWorks: [
      'Download the six tools instantly after payment.',
      'Start with the Hourly Rate Calculator, then the Job Margin Calculator.',
      'Add the quote, follow-up, planning and review tools as you go.',
    ],
    faq: [
      {
        q: 'I already bought one of these tools. Can I upgrade?',
        a: 'If it’s in your cart, the cart swaps it for the bundle automatically. If you bought it earlier, contact us with your order number and we’ll deduct what you paid.',
      },
    ],
    preview: {kind: 'bundle'},
    offer: {
      tier: 'bundle',
      problemTags: ['profit', 'organize', 'find-clients'],
      businessTags: ['artisans'],
      crossSells: [
        {handle: 'cash-flow-dashboard', priority: 80, reason: 'The finance tool that isn’t in this toolkit.'},
        {handle: 'local-visibility-bundle', priority: 70, reason: 'Get found locally once operations are in order.'},
      ],
      badges: ['featured'],
    },
  },
  {
    universe: 'pro',
    handle: 'local-visibility-bundle',
    factoryId: 'B02',
    title: 'Local Visibility Bundle',
    tagline: 'Profile, reviews, local SEO and content — everything to get found in your area.',
    priceCents: 4500,
    format: 'Bundle · 4 tools',
    formats: ['pdf', 'sheets', 'docx', 'canva'],
    timeToValue: 'Profile done this week, full plan in 30 days',
    publishedAt: '2026-05-12',
    bundleItems: [
      'google-business-profile-checklist',
      'review-request-kit',
      'local-seo-action-kit',
      'content-calendar-90-days',
    ],
    problem: {
      headline: 'Nearby clients search for what you do and find someone else.',
      points: [
        'Incomplete Google profile.',
        'Too few reviews.',
        'No local pages and no regular posts.',
      ],
    },
    outcome: {
      headline: 'The four levers of local visibility, in the order to pull them.',
      points: [
        'Complete profile in one sitting.',
        'A review routine for every finished job.',
        'A 30-day local SEO plan and 90 days of posts.',
      ],
    },
    included: [],
    howItWorks: [
      'Complete the profile checklist first.',
      'Start the review routine on your next finished job.',
      'Follow the 30-day plan, then keep posting with the calendar.',
    ],
    faq: [],
    preview: {kind: 'bundle'},
    offer: {
      tier: 'bundle',
      problemTags: ['local', 'marketing'],
      businessTags: ['artisans', 'local-shops'],
      crossSells: [
        {handle: 'follow-up-script-pack', priority: 70, reason: 'Converts the extra enquiries into signed jobs.'},
      ],
    },
  },
  {
    universe: 'pro',
    handle: 'profit-control-bundle',
    factoryId: 'B03',
    title: 'Profit Control Bundle',
    tagline: 'Rate, margin, product profit and cash flow — know where the money goes.',
    priceCents: 4900,
    format: 'Bundle · 4 tools',
    formats: ['xlsx', 'sheets', 'pdf'],
    timeToValue: 'First numbers within the hour',
    publishedAt: '2026-04-20',
    bundleItems: [
      'intervention-rate-calculator',
      'job-margin-calculator',
      'ecommerce-profit-calculator',
      'cash-flow-dashboard',
    ],
    problem: {
      headline: 'You work hard, sales look fine, and there’s still not enough left at the end of the month.',
      points: [
        'Prices set without a cost floor.',
        'Margin known only after the fact.',
        'Cash surprises every quarter.',
      ],
    },
    outcome: {
      headline: 'Four calculators that show where the profit is made and lost.',
      points: [
        'A defensible rate or product price.',
        'Margin before you commit.',
        'Cash visible 13 weeks ahead.',
      ],
    },
    included: [],
    howItWorks: [
      'Set your rate floor with the Hourly Rate Calculator.',
      'Check margins per job or per product.',
      'Put everything in the 13-week cash view.',
    ],
    faq: [],
    preview: {kind: 'bundle'},
    offer: {
      tier: 'bundle',
      problemTags: ['profit'],
      businessTags: ['artisans', 'freelancers', 'ecommerce', 'agencies'],
      crossSells: [
        {handle: 'quote-invoice-kit', priority: 80, reason: 'Gets the new prices onto clean quotes.'},
        {handle: 'freelance-pricing-workbook', priority: 60, reason: 'Packages your services around the new rate.'},
      ],
    },
  },
  {
    universe: 'pro',
    handle: 'freelance-operating-system',
    factoryId: 'B04',
    title: 'Freelance Operating System',
    tagline: 'Seven tools to price, win, onboard and get paid — the back office of a solo business.',
    priceCents: 8900,
    format: 'Bundle · 7 tools',
    formats: ['xlsx', 'sheets', 'docx', 'pdf', 'notion'],
    timeToValue: 'Set up in a weekend',
    publishedAt: '2026-08-15',
    bundleItems: [
      'intervention-rate-calculator',
      'freelance-pricing-workbook',
      'prospecting-tracker',
      'follow-up-script-pack',
      'quote-invoice-kit',
      'client-onboarding-workbook',
      'cash-flow-dashboard',
    ],
    problem: {
      headline: 'Freelancing is two jobs: the work clients pay for, and the business nobody taught you to run.',
      points: [
        'Pricing by the hour and by instinct.',
        'Leads and follow-ups scattered across apps.',
        'Messy starts and irregular cash.',
      ],
    },
    outcome: {
      headline: 'A complete back office, set up once and reused on every client.',
      points: [
        'Priced packages with a real cost floor.',
        'A pipeline with follow-ups that happen.',
        'Clean onboarding, quotes, invoices and a cash forecast.',
      ],
    },
    included: [],
    howItWorks: [
      'Weekend 1: rate, packages and pipeline.',
      'Next client: quote, onboarding and follow-up templates.',
      'Every Friday: 10 minutes on the cash dashboard.',
    ],
    faq: [],
    preview: {kind: 'bundle'},
    offer: {
      tier: 'bundle',
      problemTags: ['organize', 'find-clients', 'profit'],
      businessTags: ['freelancers', 'agencies'],
      crossSells: [
        {handle: 'content-calendar-90-days', priority: 60, reason: 'Keeps your pipeline full with regular posts.'},
      ],
      badges: ['featured'],
    },
  },

  // ================================================================ Lifestyle
  {
    universe: 'lifestyle',
    handle: 'household-budget-planner',
    factoryId: 'L01',
    title: 'Household Budget Planner',
    tagline: 'See where every euro goes each month, and what’s left to save.',
    priceCents: 1200,
    format: 'Spreadsheet planner',
    formats: ['xlsx', 'sheets', 'pdf'],
    timeToValue: '30 min to set up your first month',
    publishedAt: '2026-08-20',
    problem: {
      headline: 'The month ends before the money does, and you’re not sure where it went.',
      points: [
        'Small spending adds up without you noticing.',
        'Bills arrive on different dates and catch you out.',
        'Budgeting apps want a subscription and your bank login.',
      ],
    },
    outcome: {
      headline: 'One page that shows income, fixed bills and what you can really spend.',
      points: [
        'Monthly budget with categories you choose.',
        'Bill calendar so nothing is a surprise.',
        'Year view to spot the months that always hurt.',
      ],
    },
    included: [
      {name: 'Budget planner', format: 'xlsx', detail: 'Monthly, bills and year tabs'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Share it with your partner'},
      {name: 'Getting-started guide', format: 'pdf', detail: '4 pages'},
    ],
    howItWorks: [
      'Enter your income and fixed bills once.',
      'Log spending weekly — about 10 minutes.',
      'Read what’s left and move it to savings.',
    ],
    example: {
      title: 'Couple, two incomes, one shared account',
      setup: '€4,200 income · €2,650 fixed bills · €1,100 groceries and daily spending',
      result: '€450 a month left to save, visible on day 1 instead of day 30',
      note: EXAMPLE_NOTE,
    },
    faq: [
      {q: 'Do I need to connect my bank?', a: 'No. You enter the figures yourself; nothing leaves your file.'},
    ],
    preview: {kind: 'sheet'},
    offer: {
      tier: 'impulse',
      problemTags: ['money'],
      businessTags: [],
      crossSells: [
        {handle: 'savings-goals-tracker', priority: 100, reason: 'Puts what’s left each month toward a real goal.'},
        {handle: 'debt-payoff-planner', priority: 80, reason: 'Clears debts faster with the money you free up.'},
      ],
      bundleUpgrade: {handle: 'home-money-bundle', headline: 'Get the complete Home Money Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
      badges: ['featured'],
    },
  },
  {
    universe: 'lifestyle',
    handle: 'debt-payoff-planner',
    factoryId: 'L02',
    title: 'Debt Payoff Planner',
    tagline: 'A month-by-month plan to clear your debts, with a debt-free date.',
    priceCents: 900,
    format: 'Spreadsheet calculator',
    formats: ['xlsx', 'sheets'],
    timeToValue: '15 min',
    publishedAt: '2026-07-14',
    problem: {
      headline: 'Several loans and cards, and no idea when it will ever end.',
      points: [
        'Minimum payments barely touch the balance.',
        'You don’t know which debt to attack first.',
        'Every month feels like starting over.',
      ],
    },
    outcome: {
      headline: 'A clear order of attack and a date you can circle on the calendar.',
      points: [
        'Snowball and avalanche methods compared.',
        'Debt-free date and total interest saved.',
        'Progress chart that updates as you pay.',
      ],
    },
    included: [
      {name: 'Debt payoff planner', format: 'xlsx', detail: 'Up to 10 debts'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Copy-to-Drive link'},
    ],
    howItWorks: [
      'List each debt: balance, rate, minimum payment.',
      'Choose snowball or avalanche.',
      'Follow the monthly plan and tick off payments.',
    ],
    faq: [
      {q: 'Is this financial advice?', a: 'No. It’s a calculator that shows the effect of different repayment orders. For debt problems, a free debt-advice service in your country can help.'},
    ],
    preview: {kind: 'dashboard'},
    offer: {
      tier: 'impulse',
      problemTags: ['money'],
      businessTags: [],
      crossSells: [
        {handle: 'household-budget-planner', priority: 100, reason: 'Finds the extra money to put toward the debts.'},
        {handle: 'savings-goals-tracker', priority: 60, reason: 'Builds a buffer so new debt doesn’t creep back.'},
      ],
      bundleUpgrade: {handle: 'home-money-bundle', headline: 'Get the complete Home Money Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'lifestyle',
    handle: 'savings-goals-tracker',
    factoryId: 'L03',
    title: 'Savings Goals Tracker',
    tagline: 'Save for holidays, a car or a buffer — and watch each goal fill up.',
    priceCents: 900,
    format: 'Spreadsheet tracker',
    formats: ['xlsx', 'sheets'],
    timeToValue: '10 min',
    publishedAt: '2026-09-05',
    problem: {
      headline: 'You save “what’s left”, which usually means nothing.',
      points: [
        'No target, so no motivation.',
        'One savings pot for everything, raided for anything.',
        'Big expenses always come as a surprise.',
      ],
    },
    outcome: {
      headline: 'A pot per goal, a monthly amount per pot, and progress you can see.',
      points: [
        'Up to 8 goals with target dates.',
        'Monthly amount needed for each goal.',
        'Progress bars that fill as you save.',
      ],
    },
    included: [
      {name: 'Savings goals tracker', format: 'xlsx', detail: '8 goals, monthly view'},
      {name: 'Google Sheets version', format: 'sheets', detail: 'Works on your phone'},
    ],
    howItWorks: [
      'Name your goals and target dates.',
      'Read the monthly amount each goal needs.',
      'Log deposits and watch the bars fill.',
    ],
    faq: [],
    preview: {kind: 'dashboard'},
    offer: {
      tier: 'impulse',
      problemTags: ['money'],
      businessTags: [],
      crossSells: [
        {handle: 'household-budget-planner', priority: 100, reason: 'Shows how much you can put toward your goals.'},
      ],
      bundleUpgrade: {handle: 'home-money-bundle', headline: 'Get the complete Home Money Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'lifestyle',
    handle: 'weekly-meal-planner',
    factoryId: 'L04',
    title: 'Weekly Meal Planner & Grocery List',
    tagline: 'Plan the week’s meals in 15 minutes and shop once.',
    priceCents: 900,
    format: 'Planner + templates',
    formats: ['sheets', 'pdf', 'canva'],
    timeToValue: '15 min a week',
    publishedAt: '2026-06-25',
    problem: {
      headline: '“What’s for dinner?” every evening at 6pm.',
      points: [
        'Three trips to the shop a week.',
        'Food thrown away because nobody planned to use it.',
        'Takeaway because nothing is ready.',
      ],
    },
    outcome: {
      headline: 'A planned week and one grocery list that builds itself.',
      points: [
        'Weekly planner with a recipe bank.',
        'Grocery list grouped by shop aisle.',
        'Printable fridge planner.',
      ],
    },
    included: [
      {name: 'Meal planner', format: 'sheets', detail: 'Planner, recipe bank, grocery list'},
      {name: 'Fridge planner', format: 'pdf', detail: 'A4, printable'},
      {name: 'Editable planner', format: 'canva', detail: 'Change colours and layout'},
    ],
    howItWorks: [
      'Add the meals your household already likes.',
      'Pick meals for the week on Sunday.',
      'Shop from the generated list.',
    ],
    faq: [],
    preview: {kind: 'planner'},
    offer: {
      tier: 'impulse',
      problemTags: ['home'],
      businessTags: [],
      crossSells: [
        {handle: 'family-organiser', priority: 90, reason: 'Adds the family calendar and chores to the same routine.'},
        {handle: 'household-budget-planner', priority: 60, reason: 'Tracks the grocery money you save.'},
      ],
      bundleUpgrade: {handle: 'organised-home-bundle', headline: 'Get the complete Organised Home Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
      badges: ['featured'],
    },
  },
  {
    universe: 'lifestyle',
    handle: 'declutter-checklist',
    factoryId: 'L05',
    title: '30-Day Declutter Checklist',
    tagline: 'One small area a day — a lighter home in a month.',
    priceCents: 700,
    format: 'Checklist',
    formats: ['pdf', 'sheets'],
    timeToValue: '15 min a day',
    publishedAt: '2026-05-30',
    problem: {
      headline: 'The clutter is everywhere, so you never know where to start.',
      points: [
        'Weekend-long clear-outs that never happen.',
        'Cupboards you avoid opening.',
        'Things kept “just in case” for years.',
      ],
    },
    outcome: {
      headline: 'A daily 15-minute task, in an order that keeps you going.',
      points: [
        '30 daily tasks, easiest first.',
        'Keep / donate / sell / bin guide.',
        'Tracker to tick off each day.',
      ],
    },
    included: [
      {name: '30-day checklist', format: 'pdf', detail: 'Printable'},
      {name: 'Progress tracker', format: 'sheets', detail: 'Tick off and date each day'},
    ],
    howItWorks: [
      'Start with day 1: one drawer.',
      'Do one task a day, 15 minutes max.',
      'Use the guide for anything you hesitate on.',
    ],
    faq: [],
    preview: {kind: 'checklist'},
    offer: {
      tier: 'impulse',
      problemTags: ['home'],
      businessTags: [],
      crossSells: [
        {handle: 'family-organiser', priority: 80, reason: 'Keeps the house tidy with shared chores.'},
        {handle: 'habit-tracker', priority: 60, reason: 'Turns the daily 15 minutes into a lasting habit.'},
      ],
      bundleUpgrade: {handle: 'organised-home-bundle', headline: 'Get the complete Organised Home Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'lifestyle',
    handle: 'family-organiser',
    factoryId: 'L06',
    title: 'Family Calendar & Chore System',
    tagline: 'One shared calendar and a fair chore chart the whole family can follow.',
    priceCents: 1900,
    format: 'Planner system',
    formats: ['sheets', 'pdf', 'notion'],
    timeToValue: '45 min setup',
    publishedAt: '2026-08-02',
    problem: {
      headline: 'You’re the family’s calendar, reminder app and chore police.',
      points: [
        'Appointments and activities clash.',
        'Chores fall on the same person every week.',
        'Every morning starts with “where’s my…?”.',
      ],
    },
    outcome: {
      headline: 'Everyone knows what’s happening and what they have to do.',
      points: [
        'Shared weekly and monthly calendar.',
        'Rotating chore chart by age.',
        'Morning and evening routine cards.',
      ],
    },
    included: [
      {name: 'Family organiser', format: 'sheets', detail: 'Calendar, chores, routines'},
      {name: 'Printable charts', format: 'pdf', detail: 'Chore chart and routine cards'},
      {name: 'Notion version', format: 'notion', detail: 'Duplicate into your workspace'},
    ],
    howItWorks: [
      'Add each family member and their activities.',
      'Set up the chore rotation once.',
      'Print the week’s chart every Sunday.',
    ],
    faq: [],
    preview: {kind: 'planner'},
    offer: {
      tier: 'core',
      problemTags: ['home'],
      businessTags: [],
      crossSells: [
        {handle: 'weekly-meal-planner', priority: 90, reason: 'Adds the week’s meals to the family plan.'},
        {handle: 'habit-tracker', priority: 60, reason: 'Helps routines stick for everyone.'},
      ],
      bundleUpgrade: {handle: 'organised-home-bundle', headline: 'Get the complete Organised Home Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'lifestyle',
    handle: 'habit-tracker',
    factoryId: 'L07',
    title: 'Habit & Routine Tracker',
    tagline: 'Track up to 10 habits and see your streaks grow.',
    priceCents: 900,
    format: 'Tracker',
    formats: ['sheets', 'notion', 'pdf'],
    timeToValue: '10 min',
    publishedAt: '2026-09-10',
    problem: {
      headline: 'Good intentions every Monday, forgotten by Thursday.',
      points: [
        'Too many new habits at once.',
        'No way to see progress, so no motivation.',
        'One missed day and everything stops.',
      ],
    },
    outcome: {
      headline: 'A few habits, tracked daily, with streaks you won’t want to break.',
      points: [
        'Daily tracker for up to 10 habits.',
        'Monthly streak and completion view.',
        'Weekly review prompts.',
      ],
    },
    included: [
      {name: 'Habit tracker', format: 'sheets', detail: 'Daily, monthly and review tabs'},
      {name: 'Notion version', format: 'notion', detail: 'Duplicate into your workspace'},
      {name: 'Printable tracker', format: 'pdf', detail: 'Monthly grid'},
    ],
    howItWorks: [
      'Choose 2–3 habits to start with.',
      'Tick them off each day — 30 seconds.',
      'Review on Sunday and adjust.',
    ],
    faq: [],
    preview: {kind: 'checklist'},
    offer: {
      tier: 'impulse',
      problemTags: ['wellbeing'],
      businessTags: [],
      crossSells: [
        {handle: 'declutter-checklist', priority: 70, reason: 'A ready-made 30-day habit to start with.'},
        {handle: 'family-organiser', priority: 50, reason: 'Adds routines for the whole family.'},
      ],
      bundleUpgrade: {handle: 'organised-home-bundle', headline: 'Get the complete Organised Home Bundle'},
      progressOffer: {campaignId: '3-tools-20'},
    },
  },
  {
    universe: 'lifestyle',
    handle: 'home-money-bundle',
    factoryId: 'LB1',
    title: 'Home Money Bundle',
    tagline: 'Budget, debts and savings — the three tools to take control of your money.',
    priceCents: 2200,
    format: 'Bundle · 3 tools',
    formats: ['xlsx', 'sheets', 'pdf'],
    timeToValue: 'First budget in 30 minutes',
    publishedAt: '2026-09-06',
    bundleItems: ['household-budget-planner', 'debt-payoff-planner', 'savings-goals-tracker'],
    problem: {
      headline: 'Money stress comes from not knowing, more than from not having.',
      points: ['No clear monthly budget.', 'Debts with no end date.', 'Savings that never grow.'],
    },
    outcome: {
      headline: 'Know your numbers, clear your debts, grow your savings.',
      points: ['A monthly budget that balances.', 'A debt-free date.', 'Goals that fill up month by month.'],
    },
    included: [],
    howItWorks: [
      'Start with the budget planner.',
      'Put the money you free up toward debts.',
      'Then fill your savings goals.',
    ],
    faq: [],
    preview: {kind: 'bundle'},
    offer: {
      tier: 'bundle',
      problemTags: ['money'],
      businessTags: [],
      crossSells: [
        {handle: 'weekly-meal-planner', priority: 70, reason: 'Cuts the grocery bill, the easiest budget win.'},
      ],
      badges: ['featured'],
    },
  },
  {
    universe: 'lifestyle',
    handle: 'organised-home-bundle',
    factoryId: 'LB2',
    title: 'Organised Home Bundle',
    tagline: 'Meals, chores, clutter and routines — a calmer home in four tools.',
    priceCents: 3200,
    format: 'Bundle · 4 tools',
    formats: ['sheets', 'pdf', 'notion', 'canva'],
    timeToValue: 'Set up in an evening',
    publishedAt: '2026-08-25',
    bundleItems: ['weekly-meal-planner', 'declutter-checklist', 'family-organiser', 'habit-tracker'],
    problem: {
      headline: 'Running a home is a second job nobody sees.',
      points: ['Dinner decided at 6pm.', 'Chores on one person.', 'Clutter and routines that never stick.'],
    },
    outcome: {
      headline: 'A home that runs on a simple weekly routine.',
      points: ['Meals planned in 15 minutes.', 'Chores shared fairly.', 'Less clutter, better habits.'],
    },
    included: [],
    howItWorks: [
      'Set up the family organiser first.',
      'Plan meals every Sunday.',
      'Add the declutter and habit routines.',
    ],
    faq: [],
    preview: {kind: 'bundle'},
    offer: {
      tier: 'bundle',
      problemTags: ['home', 'wellbeing'],
      businessTags: [],
      crossSells: [
        {handle: 'household-budget-planner', priority: 70, reason: 'Adds the money side of running the house.'},
      ],
      badges: ['featured'],
    },
  },
];

export const MOCK_COLLECTIONS: CollectionDefinition[] = [
  {
    universe: 'pro',
    handle: 'find-clients',
    kind: 'problem',
    title: 'Find more clients',
    problem: 'Leads go quiet and quotes never get an answer.',
    outcome: 'Scripts and trackers that turn more of your enquiries into signed jobs.',
    filter: {universe: 'pro', problem: 'find-clients'},
    bundleHandle: 'freelance-operating-system',
  },
  {
    universe: 'pro',
    handle: 'make-more-profit',
    kind: 'problem',
    title: 'Make more profit',
    problem: 'Busy all month, and still not enough left at the end of it.',
    outcome: 'Calculators that show your real rate, your margin per job and your cash ahead.',
    filter: {universe: 'pro', problem: 'profit'},
    bundleHandle: 'profit-control-bundle',
  },
  {
    universe: 'pro',
    handle: 'get-organized',
    kind: 'problem',
    title: 'Get organized',
    problem: 'Your schedule, clients and paperwork live in your head and your inbox.',
    outcome: 'Planners and templates that put the back office on rails.',
    filter: {universe: 'pro', problem: 'organize'},
    bundleHandle: 'freelance-operating-system',
  },
  {
    universe: 'pro',
    handle: 'marketing',
    kind: 'problem',
    title: 'Marketing',
    problem: 'You post when you remember and your pages don’t convert.',
    outcome: 'Ready-to-use plans, templates and checklists for small-business marketing.',
    filter: {universe: 'pro', problem: 'marketing'},
    bundleHandle: 'local-visibility-bundle',
  },
  {
    universe: 'pro',
    handle: 'local-business',
    kind: 'problem',
    title: 'Local visibility',
    problem: 'People nearby search for what you do and find a competitor.',
    outcome: 'Profile, reviews and local SEO tools to get found in your area.',
    filter: {universe: 'pro', problem: 'local'},
    bundleHandle: 'local-visibility-bundle',
  },
  {
    universe: 'pro',
    handle: 'artisans',
    kind: 'business',
    title: 'Artisans & trades',
    problem: 'Quoting, chasing, planning and invoicing — mostly in the evening.',
    outcome: 'Tools built around jobs, crews, materials and site visits.',
    filter: {universe: 'pro', business: 'artisans'},
    bundleHandle: 'artisan-business-toolkit',
  },
  {
    universe: 'pro',
    handle: 'freelancers',
    kind: 'business',
    title: 'Freelancers',
    problem: 'Doing the client work and running the business alone.',
    outcome: 'Pricing, pipeline and onboarding tools for solo professionals.',
    filter: {universe: 'pro', business: 'freelancers'},
    bundleHandle: 'freelance-operating-system',
  },
  {
    universe: 'pro',
    handle: 'agencies',
    kind: 'business',
    title: 'Small agencies',
    problem: 'Scope creep, late payments and a pipeline that stops when you’re busy.',
    outcome: 'Tools to price, onboard and forecast a small team’s work.',
    filter: {universe: 'pro', business: 'agencies'},
    bundleHandle: 'freelance-operating-system',
  },
  {
    universe: 'pro',
    handle: 'ecommerce',
    kind: 'business',
    title: 'E-commerce',
    problem: 'Revenue grows, profit doesn’t.',
    outcome: 'Profit, cash and conversion tools for online shops.',
    filter: {universe: 'pro', business: 'ecommerce'},
    bundleHandle: 'profit-control-bundle',
  },
  {
    universe: 'pro',
    handle: 'local-shops',
    kind: 'business',
    title: 'Local shops & studios',
    problem: 'Foot traffic depends on being found online first.',
    outcome: 'Local visibility, reviews and content tools.',
    filter: {universe: 'pro', business: 'local-shops'},
    bundleHandle: 'local-visibility-bundle',
  },
  {
    universe: 'pro',
    handle: 'pro-bundles',
    kind: 'bundles',
    title: 'Pro bundles',
    problem: 'Buying business tools one by one when you need the whole set.',
    outcome: 'Complete business toolkits for less than the tools bought separately.',
    filter: {universe: 'pro', tiers: ['bundle', 'vault']},
  },
  {
    universe: 'pro',
    handle: 'pro-all',
    kind: 'all',
    title: 'All Pro tools',
    problem: 'Practical business tools. One payment. No subscription.',
    outcome: 'Every calculator, template, checklist and bundle for your business.',
    filter: {universe: 'pro'},
  },

  // ------------------------------------------------------------ Lifestyle
  {
    universe: 'lifestyle',
    handle: 'money',
    kind: 'problem',
    title: 'Budget & money',
    problem: 'The month ends before the money does, and you’re not sure where it went.',
    outcome: 'Budget, debt and savings planners that show where every euro goes.',
    filter: {universe: 'lifestyle', problem: 'money'},
    bundleHandle: 'home-money-bundle',
  },
  {
    universe: 'lifestyle',
    handle: 'home',
    kind: 'problem',
    title: 'Organised home',
    problem: 'Meals, chores and clutter take more headspace than they should.',
    outcome: 'Planners and checklists that run the house on autopilot.',
    filter: {universe: 'lifestyle', problem: 'home'},
    bundleHandle: 'organised-home-bundle',
  },
  {
    universe: 'lifestyle',
    handle: 'wellbeing',
    kind: 'problem',
    title: 'Habits & wellbeing',
    problem: 'Good intentions every Monday, forgotten by Thursday.',
    outcome: 'Simple trackers that make routines stick.',
    filter: {universe: 'lifestyle', problem: 'wellbeing'},
    bundleHandle: 'organised-home-bundle',
  },
  {
    universe: 'lifestyle',
    handle: 'lifestyle-bundles',
    kind: 'bundles',
    title: 'Lifestyle bundles',
    problem: 'Buying planners one by one when you need the whole system.',
    outcome: 'Complete home and money systems for less than the tools bought separately.',
    filter: {universe: 'lifestyle', tiers: ['bundle', 'vault']},
  },
  {
    universe: 'lifestyle',
    handle: 'lifestyle-all',
    kind: 'all',
    title: 'All Lifestyle tools',
    problem: 'Practical tools for everyday life. One payment. No subscription.',
    outcome: 'Every planner, tracker and checklist for home, money and habits.',
    filter: {universe: 'lifestyle'},
  },

  // ------------------------------------------------------------ Store-wide
  {
    handle: 'bundles',
    kind: 'bundles',
    title: 'All bundles',
    problem: 'Buying tools one by one when you need the whole set.',
    outcome: 'Every WonderWeb bundle, Pro and Lifestyle, priced below its tools bought separately.',
    filter: {tiers: ['bundle', 'vault']},
  },
  {
    handle: 'all',
    kind: 'all',
    title: 'All tools',
    problem: 'Practical tools for work and life. One payment. No subscription.',
    outcome: 'Every WonderWeb tool and bundle, Pro and Lifestyle.',
    filter: {},
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: '3-tools-20',
    type: 'cart_threshold',
    headline: 'Buy any 3 tools, get 20% off',
    eligibleTiers: ['impulse', 'core'],
    thresholdQuantity: 3,
    discountPercent: 20,
    enabled: true,
    startsAt: null,
    endsAt: null,
    // Must become 'shopify-automatic' with a matching Shopify automatic
    // discount before launch — otherwise it disappears from the live store.
    discountSource: 'mock',
  },
];
